examples/photoalbum/src/main/java/org/richfaces/photoalbum/model/Image.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2013, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
/*
 * Image.java
 * Last modified by: $Author$
 * $Revision$	$Date$
 */
package org.richfaces.photoalbum.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonAutoDetect;
import org.codehaus.jackson.annotate.JsonAutoDetect.Visibility;
import org.codehaus.jackson.annotate.JsonProperty;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;
import org.hibernate.annotations.OrderBy;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.richfaces.photoalbum.util.DateUtils;

@NamedQueries({
        @NamedQuery(name = "tag-byName", query = "select m from MetaTag m where m.tag =:tag"),
        @NamedQuery(name = "tag-popular", query = "select new org.richfaces.photoalbum.model.MetaTag(m.id, m.tag) from MetaTag m join m.images img group by m.id, m.tag order by count(img) desc"),
        @NamedQuery(name = "user-shelves", query = "select distinct s from Shelf s where (s.shared = true and s.owner.preDefined = true and s.event = null) order by s.name"),
        @NamedQuery(name = "image-exist", query = "select i from Image i where i.path = :path and i.album = :album"),
        @NamedQuery(name = "image-countIdenticalImages", query = "select count(i) from Image i where i.path like :path and i.album = :album"),
        @NamedQuery(name = "tag-suggest", query = "select m from MetaTag m where lower(m.tag) like :tag") }) // cannot use "... like lower(:tag)"
/**
 * Class for representing Image Entity
 *  EJB3 Entity Bean
 *
 * @author Andrey Markhel
 */
@Entity
@JsonAutoDetect(fieldVisibility=Visibility.NONE, getterVisibility=Visibility.NONE, isGetterVisibility=Visibility.NONE)
public class Image implements Serializable {

    private static final long serialVersionUID = -7042878411608396483L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty
    private Long id;

    @ManyToMany
    @LazyCollection(LazyCollectionOption.FALSE)
    @JsonProperty
    private List<MetaTag> imageTags = new ArrayList<MetaTag>();

    @OrderBy(clause = "date asc")
    @OneToMany(cascade = CascadeType.REMOVE, mappedBy = "image")
    @LazyCollection(LazyCollectionOption.FALSE)
    private List<Comment> comments = new ArrayList<Comment>();

    @NotNull
    @ManyToOne
    @JoinColumn
    private Album album;

    @NotNull
    @NotEmpty
    @Length(min = 3, max = 200)
    @Column(length = 255, nullable = false)
    @JsonProperty
    private String name;

    @Transient
    private boolean covering;

    @NotNull
    @NotEmpty
    @Length(min = 3)
    @Column(length = 1024, nullable = false)
    private String path;

    @Column(length = 255)
    @JsonProperty
    private String cameraModel;

    private int height;

    private double size;

    private int width;

    @Temporal(TemporalType.TIMESTAMP)
    private Date uploaded;

    @NotNull
    @NotEmpty
    @Length(min = 3)
    @Column(length = 1024)
    @JsonProperty
    private String description;

    @Temporal(TemporalType.TIMESTAMP)
    private Date created;

    @NotNull
    private boolean allowComments;

    private Boolean showMetaInfo = true;

    @Transient
    private boolean visited;

    /*
     * Comma separated tags value
     */
    @Transient
    private String meta = "";

    /**
     * Getter for property preDefined
     *
     * @return is this shelf is predefined
     */
    public boolean isPreDefined() {
        return getAlbum().isPreDefined();
    }

    // ********************** Accessor Methods ********************** //

    public Boolean getShowMetaInfo() {
        return showMetaInfo;
    }

    public void setShowMetaInfo(final Boolean showMetaInfo) {
        this.showMetaInfo = showMetaInfo;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for property path. Represent file-system structure, relative at uploadRoot dir(determined at startup, by default
     * is system temp dir) Usually is user.GetLogin() + SLASH + image.getAlbum().getId() + SLASH + fileName, for example
     * "amarkhel/15/coolPicture.jpg"
     *
     * @return relative path of image
     */
    public String getPath() {
        return path;
    }

    /**
     * Setter for property path
     *
     * @param path - relative path to image
     */
    public void setPath(String path) {
        this.path = path;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Album getAlbum() {
        return album;
    }

    public void setAlbum(Album album) {
        this.album = album;
    }

    public List<Comment> getComments() {
        return comments;
    }

    public List<MetaTag> getImageTags() {
        return imageTags;
    }

    /**
     * Setter for property meta
     *
     * @param meta - string representation of metatags, associated to image. Used at jsf page.
     */
    public void setMeta(String meta) {
        this.meta = meta;
    }

    /**
     * Getter for property meta
     *
     * @return string representation of metatags, associated to image. Used at jsf page.
     */
    public String getMetaString() {
        return meta;
    }

    public String getCameraModel() {
        return cameraModel;
    }

    public void setCameraModel(String cameraModel) {
        this.cameraModel = cameraModel;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    /**
     * Getter for property size
     *
     * @return size of image in KB
     */
    public double getSize() {
        return size;
    }

    /**
     * setter for property size
     *
     * @param size - size of image in KB
     */
    public void setSize(double size) {
        this.size = size;
    }

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    /**
     * Getter for property uploaded
     *
     * @return date of upload to site of this image
     */
    public Date getUploaded() {
        return uploaded;
    }

    /**
     * setter for property uploaded
     *
     * @param uploaded - date of upload
     */
    public void setUploaded(Date uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * Getter for property allowComments. If true, other user may comment this image.
     *
     * @return is other users may comment this image
     */
    public boolean isAllowComments() {
        return allowComments;
    }

    /**
     * @param allowComments the allowComments to set
     */
    public void setAllowComments(boolean allowComments) {
        this.allowComments = allowComments;
    }

    /**
     * @return if this image is covering for containing album
     */
    public boolean isCovering() {
        return covering;
    }

    public void setImageTags(final List<MetaTag> imageTags) {
        this.imageTags = imageTags;
    }

    /**
     * @param covering - determine if this image is covering for containing album
     */
    public void setCovering(boolean covering) {
        this.covering = covering;
    }

    /**
     * Getter for property visited
     *
     * @return boolean value, that indicated is user visit this image already
     */
    public boolean isVisited() {
        return visited;
    }

    /**
     * Setter for property visited
     *
     * @param visited - boolean value, that indicated is user visit this image already
     */
    public void setVisited(boolean visited) {
        this.visited = visited;
    }

    /**
     * Determine if this image should be marked as new(on jsf page, for example in tree)
     *
     * @return boolean value, that indicated is this image should be marked as new
     */
    public boolean isNew() {
        if (!visited) {

examples/photoalbum/src/main/java/org/richfaces/photoalbum/manager/UserBean.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2013, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

package org.richfaces.photoalbum.manager;

import static org.richfaces.photoalbum.model.event.Events.ADD_ERROR_EVENT;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.event.Event;
import javax.enterprise.inject.Produces;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.richfaces.photoalbum.model.User;
import org.richfaces.photoalbum.model.event.ErrorEvent;
import org.richfaces.photoalbum.model.event.EventType;
import org.richfaces.photoalbum.social.facebook.FacebookBean;
import org.richfaces.photoalbum.social.gplus.GooglePlusBean;
import org.richfaces.photoalbum.util.Constants;
import org.richfaces.photoalbum.util.Preferred;

/**
 * This bean will work as a part of a simple security checking
 *
 * @author mpetrov
 */

@Named
@SessionScoped
public class UserBean implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    EntityManager em;

    @Inject
    UserManager um;

    private User user;

    private String username;

    private String fbPhotoUrl;

    @Inject
    FacebookBean fbBean;

    @Inject
    GooglePlusBean gPlusBean;

    @Inject
    @EventType(ADD_ERROR_EVENT)
    Event<ErrorEvent> event;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    private String password;

    private boolean logged = false;

    private boolean loggedInFB = false;
    private boolean loggedInGPlus = false;

    public User logIn(String username, String passwordHash) throws Exception {
        user = (User) em.createNamedQuery(Constants.USER_LOGIN_QUERY).setParameter(Constants.USERNAME_PARAMETER, username)
            .setParameter(Constants.PASSWORD_PARAMETER, passwordHash).getSingleResult();
        logged = user != null;

        return user;
    }

    public User facebookLogIn(String facebookId) {
        if (!logged) { // user is not logged, trying to log in with Facebook credentials
            List<?> users = em.createNamedQuery(Constants.USER_FB_LOGIN_QUERY).setParameter("fbId", facebookId).getResultList();

            if (users.isEmpty()) {
                logged = false;
                loggedInFB = false;
                return null;
            }

            user = (User) users.get(0);
        }

        logged = true;
        loggedInFB = true;

        return user;
    }

    public User gPlusLogIn(String gPlusId) {
        if (!logged) {
            List<?> users = em.createNamedQuery(Constants.USER_GPLUS_LOGIN_QUERY).setParameter("gPlusId", gPlusId)
                .getResultList();

            if (users.isEmpty()) {
                logged = false;
                loggedInGPlus = false;
                return null;
            }

            user = (User) users.get(0);
        }

        logged = true;
        loggedInGPlus = true;

        return user;
    }

    @Produces
    @Preferred
    public User getUser() {
        if (!logged) {
            return null;
        }
        return user;
    }

    public void refreshUser() {
        if (logged) {
            user = em.find(User.class, user.getId());
            logged = user != null;
        }
    }

    public boolean isLoggedIn() {
        return logged;
    }

    public boolean isLoggedInFB() {
        return loggedInFB;
    }

    public boolean isLoggedInGPlus() {
        return loggedInGPlus;
    }

    public void logout() {
        user = null;
        logged = false;
        loggedInFB = false;
        fbPhotoUrl = "";
        loggedInGPlus = false;
    }

    public void reset() {
        username = "";
        password = "";
    }

    public String getFbPhotoUrl() {
        return fbPhotoUrl;
    }

    public void setFbPhotoUrl(String fbPhotoUrl) {
        this.fbPhotoUrl = fbPhotoUrl;
    }

    @Override
    public String toString() {
        return "UserBean{" + "user=" + user + ", logged=" + logged + '}';
    }

    public String getFbId() {
        return user.getFbId().equals("1") ? fbBean.getUserId() : "1";
    }

    public String getGplusId() {
        return user.getgPlusId().equals("1") ? gPlusBean.getUserId() : "1";
    }
}

examples/photoalbum/src/main/webapp/includes/image/albumPanel.xhtml
<!--
  JBoss, Home of Professional Open Source
  Copyright 2013, Red Hat, Inc. and individual contributors
  by the @authors tag. See the copyright.txt in the distribution for a
  full listing of individual contributors.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions" xmlns:rich="http://richfaces.org/rich"
    xmlns:a4j="http://richfaces.org/a4j" xmlns:richx="http://richfaces.org/richx">

    <rich:popupPanel id="albumsPopupPanel" minHeight="300" minWidth="500" rendered="#{userBean.loggedInFB}"
        onshow="if(!#{facebookAlbumCache.loaded}){F.getAllAlbums(loadFBAlbums, showError);}">
        <f:facet name="header">
            <h:outputText value="Choose album to share to" />
        </f:facet>
        <f:facet name="controls">
            <h:panelGroup>
                <h:graphicImage value="resources/img/modal/close.png" style="cursor:pointer">
                    <rich:componentControl target="albumsPopupPanel" operation="hide" event="click" />
                </h:graphicImage>
            </h:panelGroup>
        </f:facet>
        <rich:hotKey key="esc" onkeyup="#{rich:component('albumsPopupPanel')}.hide()" />
        <a4j:mediaOutput id="imgUri" style="display:none" element="a" createContent="#{directLinkHelper.paintImage}"
            value="#{model.selectedImage.id}" mimeType="image/jpeg" />

        <a4j:outputPanel id="fbAlbums">
            <h:outputText value="Loading albums, please wait."
                rendered="#{!facebookAlbumCache.loaded}" />
            <h:outputText value="No available albums. Log into Facebook and create one."
                rendered="#{facebookAlbumCache.loaded and facebookAlbumCache.emptyCache}" />
            <rich:dataGrid rendered="#{fn:length(facebookAlbumCache.getAlbums()) > 0}"
                value="#{facebookAlbumCache.getAlbums()}" var="album" columns="3">
                <rich:panel header="#{album.getString('name')}">
                    <a4j:commandLink execute="@none"
                        onclick="F.pushImage('#{album.getString('id')}', #{rich:element('imgUri')}.href, '#{model.selectedImage.description}', showError); #{rich:component('albumsPopupPanel')}.hide()">
                        <img src="#{album.getString('coverUrl')}" />
                    </a4j:commandLink>
                </rich:panel>
            </rich:dataGrid>
        </a4j:outputPanel>
        <a4j:jsFunction name="loadFBAlbums" render="fbAlbums">
            <a4j:param assignTo="#{facebookAlbumCache.all}" name="albums" />
        </a4j:jsFunction>
    </rich:popupPanel>
</ui:composition>

examples/photoalbum/src/main/webapp/includes/image/imageAdditionalInfo.xhtml
<!--
  JBoss, Home of Professional Open Source
  Copyright 2013, Red Hat, Inc. and individual contributors
  by the @authors tag. See the copyright.txt in the distribution for a
  full listing of individual contributors.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:a4j="http://richfaces.org/a4j"
                xmlns:rich="http://richfaces.org/rich" xmlns:richx="http://richfaces.org/richx">
    <h:panelGroup layout="block" style="margin-top : 20px">
        <h:outputText styleClass="bold" value="#{messages['tags']}: " />
        <a4j:repeat value="#{model.selectedImage.imageTags}" var="tag">
            <a4j:commandLink actionListener="#{controller.showTag(tag)}" render="mainArea" value="#{tag.tag}" />
            <h:outputText value=" " />
        </a4j:repeat>
    </h:panelGroup>

    <h:panelGroup rendered="#{model.selectedImage.allowComments}" layout="block" id="commentPanel"
                  style="margin-top : 30px; width:100%;">
        <h:panelGroup style="padding-bottom:15px;">
            <h:outputText styleClass="bold" value="#{messages['comment.comments']}:" />
        </h:panelGroup>

        <a4j:repeat value="#{model.selectedImage.comments}" var="comment">
            <h:panelGroup layout="block" style="clear:both; padding-bottom:10px;padding-top:10px;" class="comment">
                <h:panelGroup layout="block" styleClass="preview_box_photo_nav" style="margin-right : 5px; float:left;">
                    <h:graphicImage styleClass="pr_photo_bg" value="resources/img/shell/frame_photo_200.png" />
                    <h:panelGrid cellpadding="0">
                        <h:panelGroup>
                            <a4j:commandLink render="mainArea" actionListener="#{controller.showUser(comment.author)}">
                                <a4j:mediaOutput rendered="#{comment.author.hasAvatar}" element="img"
                                                 createContent="#{imageLoader.paintImage}" styleClass="additional-info-avatar"
                                                 value="/#{comment.author.login}/avatar.jpg" mimeType="image/jpeg" />
                                <h:graphicImage rendered="#{!comment.author.hasAvatar and comment.author.sex.key =='1' }"
                                                value="resources/img/shell/avatar_default.png" width="80" height="80" alt="" style="border:none" />
                                <h:graphicImage rendered="#{!comment.author.hasAvatar and comment.author.sex.key =='0' }"
                                                value="resources/img/shell/avatar_w_default.png" width="80" height="80" alt="" style="border:none" />
                            </a4j:commandLink>
                            <br />
                        </h:panelGroup>
                    </h:panelGrid>
                </h:panelGroup>

                <h:panelGroup layout="block" styleClass="comment-deleteLink">
                    <h:panelGroup rendered="#{comment.author == userBean.user}" layout="block"
                                  styleClass="additional-info-comment-del">
                        <a4j:commandLink value="#{messages['comment.delete']}"
                                         actionListener="#{imageManager.deleteComment(comment)}" render="commentPanel" />
                    </h:panelGroup>
                    <h:panelGroup layout="block">
                        <h:outputText styleClass="bold" value="#{comment.author.login} " />
                        <h:outputText styleClass="additional-info-text" value="#{comment.date}">
                            <f:convertDateTime />
                        </h:outputText>
                    </h:panelGroup>
                </h:panelGroup>
                <h:panelGroup style="width:600px;overflow-x:auto;" layout="block" styleClass="comment-text">
                    <h:outputText escape="false" value="#{comment.message}" />
                </h:panelGroup>
            </h:panelGroup>
        </a4j:repeat>
        <h:panelGroup layout="block" style="padding-top:10px; clear:both">
            <a4j:region rendered="#{userBean.loggedIn}" id="commentEditor">
                <h:panelGroup layout="block" id="editContent">
                    <!-- TODO: add configuration -->
                    <rich:editor value="#{imageManager.message}" toolbar="basic" id="editor2" width="400" height="200" />
                </h:panelGroup>
            </a4j:region>
        </h:panelGroup>
        <richx:commandButton rendered="#{userBean.loggedIn}" value="#{messages['comment.add']}"
                             actionListener="#{imageManager.addComment(model.selectedImage)}" render="commentPanel" execute="commentEditor" />
    </h:panelGroup>
    <h:panelGroup rendered="#{!model.selectedImage.allowComments}" layout="block" id="commentPanel2" style="margin-top : 30px">
        <h:outputText styleClass="bold" value="#{messages['comments_for_this_photo_is_not_allowed']}" />
    </h:panelGroup>
</ui:composition>

examples/photoalbum/src/main/webapp/includes/image/imageHeaderInfo.xhtml
<!--
  JBoss, Home of Professional Open Source
  Copyright 2013, Red Hat, Inc. and individual contributors
  by the @authors tag. See the copyright.txt in the distribution for a
  full listing of individual contributors.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
                xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich"
                xmlns:richx="http://richfaces.org/richx"
                xmlns:c="http://java.sun.com/jsp/jstl/core">
    <a4j:outputPanel id="imageHeader">
        <h:panelGrid styleClass="image-header-table" style="padding: 0">
            <h:panelGroup>
                <a4j:commandLink styleClass="additional-info-text" actionListener="#{controller.showShelf(model.selectedShelf)}"
                                 render="mainArea, treePanel" value="#{messages['shelf']} #{model.selectedShelf.name}" />
                <h:outputText value=" #{messages['delimiter']} " />
                <a4j:commandLink styleClass="additional-info-text" actionListener="#{controller.showAlbum(model.selectedAlbum)}"
                                 render="mainArea, treePanel" value="#{messages['album']} #{model.selectedAlbum.name}" />
                <br/>
                <br/>
                <h1>
                    <c:choose>
                        <c:when test="#{controller.isUserImage(model.selectedImage)}">
                            <rich:inplaceInput value="#{model.selectedImage.name}" inputWidth="570">
                                <a4j:ajax event="change" render="mainArea" listener="#{imageManager.editImage(model.selectedImage,true)}"/>
                            </rich:inplaceInput>
                        </c:when>
                        <c:otherwise>
                            <h:outputText value="#{model.selectedImage.name}"/>
                        </c:otherwise>
                    </c:choose>
                </h1>
            </h:panelGroup>
        </h:panelGrid>
        <p>
            <h:outputText styleClass="description" value="#{model.selectedImage.description}" escape="#{!model.selectedImage.owner.preDefined}"/>
        </p>
    </a4j:outputPanel>
</ui:composition>

examples/photoalbum/src/main/webapp/includes/image/imageInfo.xhtml
<!--
  JBoss, Home of Professional Open Source
  Copyright 2013, Red Hat, Inc. and individual contributors
  by the @authors tag. See the copyright.txt in the distribution for a
  full listing of individual contributors.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:a4j="http://richfaces.org/a4j"
    xmlns:rich="http://richfaces.org/rich" xmlns:richx="http://richfaces.org/richx">
    <ui:include src="/includes/image/imageHeaderInfo.xhtml" />
    <ui:include src="/includes/image/imageGeneralInfo.xhtml" />
    <ui:include src="/includes/image/imageAdditionalInfo.xhtml" />
</ui:composition>