examples/components-demo/src/main/java/org/richfaces/demo/input/CalendarBean.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2013, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

package org.richfaces.demo.input;

import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ValueChangeEvent;

import org.richfaces.component.Positioning;
import org.richfaces.event.CurrentDateChangeEvent;

@ManagedBean
@SessionScoped
public class CalendarBean {
    private Locale locale;
    private boolean popup;
    private String pattern;
    private Date selectedDate;
    private boolean showApply = true;
    private boolean useCustomDayLabels;
    private String mode = "client";
    private Positioning jointPoint = Positioning.DEFAULT;
    private Positioning direction = Positioning.DEFAULT;
    private int horizontalOffset = 0;
    private int verticalOffset = 0;
    private Positioning[] positioningValues = Positioning.values();
    private TimeZone timeZone = TimeZone.getTimeZone("EST");

    public CalendarBean() {

        locale = Locale.US;
        popup = true;
        pattern = "d/M/yy HH:mm";
    }

    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
    }

    public Locale getLocale() {
        return locale;
    }

    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    public boolean isPopup() {
        return popup;
    }

    public void setPopup(boolean popup) {
        this.popup = popup;
    }

    public String getPattern() {
        return pattern;
    }

    public void setPattern(String pattern) {
        this.pattern = pattern;
    }

    public void selectLocale(ValueChangeEvent event) {

        String tLocale = (String) event.getNewValue();
        if (tLocale != null) {
            String lang = tLocale.substring(0, 2);
            String country = tLocale.substring(3);
            locale = new Locale(lang, country, "");
        }
    }

    public boolean isUseCustomDayLabels() {
        return useCustomDayLabels;
    }

    public void setUseCustomDayLabels(boolean useCustomDayLabels) {
        this.useCustomDayLabels = useCustomDayLabels;
    }

    public Date getSelectedDate() {
        return selectedDate;
    }

    public void setSelectedDate(Date selectedDate) {
        this.selectedDate = selectedDate;
    }

    public boolean isShowApply() {
        return showApply;
    }

    public void setShowApply(boolean showApply) {
        this.showApply = showApply;
    }

    public void setJointPoint(Positioning jointPoint) {
        this.jointPoint = jointPoint;
    }

    public Positioning getJointPoint() {
        return jointPoint;
    }

    public void setDirection(Positioning direction) {
        this.direction = direction;
    }

    public Positioning getDirection() {
        return direction;
    }

    public void setHorizontalOffset(int horizontalOffset) {
        this.horizontalOffset = horizontalOffset;
    }

    public int getHorizontalOffset() {
        return horizontalOffset;
    }

    public void setVerticalOffset(int verticalOffset) {
        this.verticalOffset = verticalOffset;
    }

    public int getVerticalOffset() {
        return verticalOffset;
    }

    public void doValueChangeListener(ValueChangeEvent event) {
        System.out
                .println("doValueChangeListener: old value = " + event.getOldValue() + ", new value = " + event.getNewValue());
    }

    public void doCurrentDataChangeListener(CurrentDateChangeEvent event) {
        System.out.println("doCurrentDataChangeListener: " + event.getCurrentDateString());
    }

    public Positioning[] getPositioningValues() {
        return positioningValues;
    }

    public void setTimeZone(TimeZone timeZone) {
        this.timeZone = timeZone;
    }

    public TimeZone getTimeZone() {
        return timeZone;
    }
}

examples/components-demo/src/main/java/org/richfaces/demo/input/CountriesBean.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2013, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.richfaces.demo.input;

import java.net.URL;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.FacesException;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author nick
 *
 */
@ManagedBean(eager = true)
@ApplicationScoped
public class CountriesBean {
    private List<Country> countries;

    @XmlRootElement(name = "countries", namespace = Country.NAMESPACE)
    private static class Countries {
        @XmlElement(name = "country", namespace = Country.NAMESPACE)
        private List<Country> countries;

        public List<Country> getCountries() {
            return countries;
        }
    }

    public CountriesBean() {
    }

    @PostConstruct
    public void initialize() {
        try {
            JAXBContext countryContext = JAXBContext.newInstance(Countries.class);
            Unmarshaller unmarshaller = countryContext.createUnmarshaller();

            countries = ((Countries) unmarshaller.unmarshal(CountriesBean.class.getResource("countries.xml"))).getCountries();
        } catch (JAXBException e) {
            throw new FacesException(e.getMessage(), e);
        }
    }

    public List<Country> getCountries() {
        return countries;
    }
}

examples/components-demo/src/main/java/org/richfaces/demo/input/FileUploadBean.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2013, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.richfaces.demo.input;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.event.AbortProcessingException;
import javax.faces.event.AjaxBehaviorEvent;

import org.richfaces.model.UploadedFile;
import org.richfaces.event.FileUploadEvent;

/**
 * @author Konstantin Mishin
 *
 */
@ManagedBean
@SessionScoped
public class FileUploadBean {
    private String acceptedTypes = "png";
    private boolean disabled = false;
    private boolean noDuplicate = false;
    private UploadedFile file;
    private List<UploadedFile> files = new ArrayList<UploadedFile>();
    private String clearedFile;
    private String ontyperejected = "alert('typerejected')";
    private Integer maxFilesQuantity = 2;
    private boolean immediateUpload = false;

    public UploadedFile getFile() {
        return file;
    }

    public List<UploadedFile> getFiles() {
        return files;
    }

    public void setFiles(List<UploadedFile> files) {
        this.files = files;
    }

    public String getClearedFile() {
        return clearedFile;
    }

    public void setClearedFile(String clearedFile) {
        this.clearedFile = clearedFile;
    }

    public void clearFile() {
        System.out.println("Files to clear: " + this.clearedFile);
        Iterator<UploadedFile> i = files.iterator();
        while (i.hasNext()) {
            UploadedFile file = i.next();
            if (file.getName().equals(this.clearedFile)) {
                i.remove();
                break;
            }
        }
    }

    public void listener(FileUploadEvent event) throws Exception {
        file = event.getUploadedFile();
        files.add(file);
    }

    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }

    public boolean isDisabled() {
        return disabled;
    }

    public void setNoDuplicate(boolean noDuplicate) {
        this.noDuplicate = noDuplicate;
    }

    public boolean isNoDuplicate() {
        return noDuplicate;
    }

    public void setAcceptedTypes(String acceptedTypes) {
        this.acceptedTypes = acceptedTypes;
    }

    public String getAcceptedTypes() {
        return acceptedTypes;
    }

    public String getOntyperejected() {
        return ontyperejected;
    }

    public void setOntyperejected(String ontyperejected) {
        this.ontyperejected = ontyperejected;
    }

    public Integer getMaxFilesQuantity() {
        return maxFilesQuantity;
    }

    public void setMaxFilesQuantity(Integer maxFilesQuantity) {
        this.maxFilesQuantity = maxFilesQuantity;
    }

    public boolean isImmediateUpload() {
        return immediateUpload;
    }

    public void setImmediateUpload(boolean immediateUpload) {
        this.immediateUpload = immediateUpload;
    }

    public void updateAttribute(AjaxBehaviorEvent event) throws AbortProcessingException {
        UIComponent component = (UIComponent) event.getSource();
        String attributeName = (String) component.findComponent("name").getAttributes().get("value");
        Object attributeValue = component.findComponent("value").getAttributes().get("value");
        component.findComponent("fu").getAttributes().put(attributeName, attributeValue);
    }
}

examples/components-demo/src/main/java/org/richfaces/demo/input/InputNumberSliderBean.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2013, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.richfaces.demo.input;

import org.richfaces.component.InputNumberSliderHandleType;
import org.richfaces.component.InputNumberSliderInputPosition;

import java.util.Date;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;


@ManagedBean(name = "inputNumberSliderBean")
@SessionScoped
public class InputNumberSliderBean {
    private double value;
    private String accesskey;
    private int delay = 200;
    private boolean disabled = false;
    private boolean enableManualInput = true;
    private InputNumberSliderInputPosition inputPosition = InputNumberSliderInputPosition.right;
    private int inputSize = 3;
    private double maxValue = 100;
    private double minValue = 0;
    private boolean showArrows = false;
    private boolean showBoundaryValues = true;
    private boolean showInput = true;
    private boolean showTooltip = true;
    private double step = 1;
    private InputNumberSliderHandleType handleType;

    public void setValue(double value) {
        this.value = value;
    }

    public double getValue() {
        return value;
    }

    public void setAccesskey(String accesskey) {
        this.accesskey = accesskey;
    }

    public String getAccesskey() {
        return accesskey;
    }

    public int getDelay() {
        return delay;
    }

    public void setDelay(int delay) {
        this.delay = delay;
    }

    public void setEnableManualInput(boolean enableManualInput) {
        this.enableManualInput = enableManualInput;
    }

    public boolean getEnableManualInput() {
        return enableManualInput;
    }

    public void setInputPosition(InputNumberSliderInputPosition inputPosition) {
        this.inputPosition = inputPosition;
    }

    public InputNumberSliderInputPosition getInputPosition() {
        return inputPosition;
    }

    public InputNumberSliderInputPosition[] getPositionTypes() {
        return InputNumberSliderInputPosition.values();
    }

    public double getMaxValue() {
        return maxValue;
    }

    public void setMaxValue(double maxValue) {
        this.maxValue = maxValue;
    }

    public double getMinValue() {
        return minValue;
    }

    public void setMinValue(double minValue) {
        this.minValue = minValue;
    }

    public boolean isShowArrows() {
        return showArrows;
    }

    public void setShowArrows(boolean showArrows) {
        this.showArrows = showArrows;
    }

    public boolean isShowBoundaryValues() {
        return showBoundaryValues;
    }

    public void setShowBoundaryValues(boolean showBoundaryValues) {
        this.showBoundaryValues = showBoundaryValues;
    }

    public boolean isShowInput() {
        return showInput;
    }

    public void setShowInput(boolean showInput) {
        this.showInput = showInput;
    }

    public boolean isShowTooltip() {
        return showTooltip;
    }

    public void setShowTooltip(boolean showTooltip) {
        this.showTooltip = showTooltip;
    }

    public double getStep() {
        return step;
    }

    public void setStep(double step) {
        this.step = step;
    }

    public void setDisabled(boolean disabled) {
        this.disabled = disabled;
    }

    public boolean isDisabled() {
        return disabled;
    }

    public void setInputSize(int inputSize) {
        this.inputSize = inputSize;
    }

    public int getInputSize() {
        return inputSize;
    }

    public Date getDate() {
        return new Date();
    }

    public InputNumberSliderHandleType getHandleType() {
        return handleType;
    }

    public void setHandleType(InputNumberSliderHandleType handleType) {
        this.handleType = handleType;
    }

    public InputNumberSliderHandleType[] getHandleTypes() {
        return InputNumberSliderHandleType.values();
    }
}

examples/components-demo/src/main/webapp/examples/input/autocomplete.xhtml
<!--
  JBoss, Home of Professional Open Source
  Copyright 2013, Red Hat, Inc. and individual contributors
  by the @authors tag. See the copyright.txt in the distribution for a
  full listing of individual contributors.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<ui:composition template="/layout/template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j">
<ui:param name="title" value="Autocomplete" />

<ui:define name="content">
    
    <h3>Autocomplete with custom suggestion formatting in list layout</h3>
    
    Following sample shows usage of autocomplete in AJAX mode with custom suggestion formatting and fetched value:
    
    <h:form id="custom-formatting">
    	<rich:autocomplete id="autocomplete" autocompleteMethod="#{autocompleteBean.suggest}" mode="cachedAjax" minChars="2" selectFirst="true" var="p" fetchValue="#{p.name}"
            onblur="console.log('blur')">
            <span>#{p.name} - #{p.age}</span>
        </rich:autocomplete>
        
        <a4j:commandButton render="autocomplete" value="Re-render" />
    </h:form>
    
    <h3>Autocomplete with suggestion in table layout</h3>
    
    <h:form id="table-layout">
        <rich:autocomplete id="autocomplete" autocompleteMethod="#{autocompleteBean.suggest}" mode="ajax" var="p" fetchValue="#{p.name}">
            <rich:column>
                #{p.name}
            </rich:column>
            <rich:column>
                #{p.age}
            </rich:column>
        </rich:autocomplete>
        
        <a4j:commandButton render="autocomplete" value="Re-render" />
    </h:form>

</ui:define>
</ui:composition>

examples/components-demo/src/main/webapp/examples/input/fileupload-rf-11977.xhtml
<!--
  JBoss, Home of Professional Open Source
  Copyright 2013, Red Hat, Inc. and individual contributors
  by the @authors tag. See the copyright.txt in the distribution for a
  full listing of individual contributors.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<ui:composition template="/layout/template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j">
    <ui:param name="title" value="File Upload - RF-11977" />


    <!-- content -->
    <ui:define name="content">
        <h:form id="form">

            <rich:panel>
                <rich:fileUpload id="uploadFile1"
                               fileUploadListener="#{richFileUploadBean2.listener}"
                               maxFilesQuantity="1"
                               immediateUpload="true"
                               listHeight="65px"/>
            </rich:panel>

            <rich:panel>
                <rich:fileUpload id="uploadFile2"
                               fileUploadListener="#{richFileUploadBean2.listener2}"
                               maxFilesQuantity="1"
                               immediateUpload="true"
                               listHeight="65px"/>
            </rich:panel>

            <!-- rich:panel>
                <a4j:commandButton id="addB" value="value" action="#{bean.method3}"
                    render="stg" />
            </rich:panel-->
        </h:form>
    </ui:define>
</ui:composition>

examples/components-demo/src/main/webapp/examples/input/index.xhtml
<!DOCTYPE html>
<!--
  JBoss, Home of Professional Open Source
  Copyright 2013, Red Hat, Inc. and individual contributors
  by the @authors tag. See the copyright.txt in the distribution for a
  full listing of individual contributors.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j">

<ui:composition template="/layout/template.xhtml">
    <ui:param name="title" value="Input Components" />
    <!-- content -->
    <ui:define name="content">
        <h2>Developer example</h2>
    </ui:define>
</ui:composition>
</html>

examples/components-demo/src/main/webapp/examples/input/inputNumberSlider.xhtml
<!--
  JBoss, Home of Professional Open Source
  Copyright 2013, Red Hat, Inc. and individual contributors
  by the @authors tag. See the copyright.txt in the distribution for a
  full listing of individual contributors.

  This is free software; you can redistribute it and/or modify it
  under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the License, or (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this software; if not, write to the Free
  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<ui:composition template="/layout/template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:a4j="http://richfaces.org/a4j">
    <ui:param name="title" value="Input Number Slider" />


    <!-- content -->
    <ui:define name="content">
        <h:form id="form">
            <h:outputText value="Skin: "/>
            <h:selectOneMenu value="#{skinBean.skin}" onchange="submit();">
                <f:selectItems value="#{skinBean.skinSetItems}"/>
            </h:selectOneMenu>
            <br/>
            <h:outputText value="Date: "/>
            <h:outputText id="date" value="#{inputNumberSliderBean.date}"/>
            <br/>
            <rich:inputNumberSlider id="ins" value="#{inputNumberSliderBean.value}"
                                   accesskey="#{inputNumberSliderBean.accesskey}"
                                   delay="#{inputNumberSliderBean.delay}" disabled="#{inputNumberSliderBean.disabled}"
                                   enableManualInput="#{inputNumberSliderBean.enableManualInput}"
                                   inputPosition="#{inputNumberSliderBean.inputPosition}"
                                   inputSize="#{inputNumberSliderBean.inputSize}"
                                   showArrows="#{inputNumberSliderBean.showArrows}"
                                   showBoundaryValues="#{inputNumberSliderBean.showBoundaryValues}"
                                   showInput="#{inputNumberSliderBean.showInput}"
                                   showTooltip="#{inputNumberSliderBean.showTooltip}"
                                   maxValue="#{inputNumberSliderBean.maxValue}"
                                   minValue="#{inputNumberSliderBean.minValue}"
                                   step="#{inputNumberSliderBean.step}"
                                   handleType="#{inputNumberSliderBean.handleType}">
                <f:ajax render="date"/>
            </rich:inputNumberSlider>
            <br/>
            <h:outputText value="Accesskey: "/>
            <h:inputText value="#{inputNumberSliderBean.accesskey}">
                <f:ajax render="ins"/>
            </h:inputText>
            <br/>
            <h:outputText value="EnableManualInput: "/>
            <h:selectBooleanCheckbox value="#{inputNumberSliderBean.enableManualInput}">
                <f:ajax render="ins"/>
            </h:selectBooleanCheckbox>
            <br/>
            <h:outputText value="Disabled "/>
            <h:selectBooleanCheckbox value="#{inputNumberSliderBean.disabled}">
                <f:ajax render="ins"/>
            </h:selectBooleanCheckbox>
            <br/>
            <h:outputText value="Delay: "/>
            <h:inputText value="#{inputNumberSliderBean.delay}">
                <f:ajax render="ins"/>
            </h:inputText>
            <br/>
            <h:outputText value="InputPosition: "/>
            <h:selectOneMenu value="#{inputNumberSliderBean.inputPosition}">
                <f:selectItems value="#{inputNumberSliderBean.positionTypes}"/>
                <f:ajax render="ins"/>
            </h:selectOneMenu>
            <br/>
            <h:outputText value="InputSize: "/>
            <h:inputText value="#{inputNumberSliderBean.inputSize}">
                <f:ajax render="ins"/>
            </h:inputText>
            <br/>
            <h:outputText value="MaxValue: "/>
            <h:inputText value="#{inputNumberSliderBean.maxValue}">
                <f:ajax render="ins"/>
            </h:inputText>
            <br/>
            <h:outputText value="MinValue: "/>
            <h:inputText value="#{inputNumberSliderBean.minValue}">
                <f:ajax render="ins"/>
            </h:inputText>
            <br/>
            <h:outputText value="ShowArrows: "/>
            <h:selectBooleanCheckbox value="#{inputNumberSliderBean.showArrows}">
                <f:ajax render="ins"/>
            </h:selectBooleanCheckbox>
            <br/>
            <h:outputText value="ShowBoundaryValues: "/>
            <h:selectBooleanCheckbox value="#{inputNumberSliderBean.showBoundaryValues}">
                <f:ajax render="ins"/>
            </h:selectBooleanCheckbox>
            <br/>
            <h:outputText value="ShowInput: "/>
            <h:selectBooleanCheckbox value="#{inputNumberSliderBean.showInput}">
                <f:ajax render="ins"/>
            </h:selectBooleanCheckbox>
            <br/>
            <h:outputText value="ShowTooltip: "/>
            <h:selectBooleanCheckbox value="#{inputNumberSliderBean.showTooltip}">
                <f:ajax render="ins"/>
            </h:selectBooleanCheckbox>
            <br/>
            <h:outputText value="Step: "/>
            <h:inputText value="#{inputNumberSliderBean.step}">
                <f:ajax render="ins"/>
            </h:inputText>
            <br />
            <h:selectOneMenu value="#{inputNumberSliderBean.handleType}">
                <f:selectItems value="#{inputNumberSliderBean.handleTypes}"/>
                <f:ajax render="ins"/>
            </h:selectOneMenu>
        </h:form>
    </ui:define>
</ui:composition>